### ISSUE TITLE
UHC run latest version . 

### ISSUE THREAD

**Issue by salem017** [Galli24/UHCRun#1]
I am in craftbukkit 1.7.10 , can you take the plugin and create a update for 1.7.10 ?  Because there are errors of chunks.

Thank for you

**Comment by Galli24** [comment]
Make sure that you make a new world, the plugin was made for 1.8, post the log of the chunk errors and I'll see if I will make a 1.7.10 version, or maybe they already exist in the 1.8 version in which case would be helpful so I can fix them

**Comment by Galli24** [comment]
No reply
#Closed

**Comment by salem017** [comment]
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 04/06/15 07:10
Description: Exception in server tick loop

java.lang.NoSuchMethodError: org.bukkit.block.Block.setType(Lorg/bukkit/Material;Z)V
	at com.galli24.uhcrun.blockpopulator.OrePopulator.makeOres(OrePopulator.java:62)
	at com.galli24.uhcrun.blockpopulator.OrePopulator.populate(OrePopulator.java:45)
	at net.minecraft.server.v1_7_R4.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:281)
	at net.minecraft.server.v1_7_R4.Chunk.loadNearby(Chunk.java:851)
	at org.bukkit.craftbukkit.v1_7_R4.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:66)
	at org.bukkit.craftbukkit.v1_7_R4.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:13)
	at org.bukkit.craftbukkit.v1_7_R4.util.AsynchronousExecutor$Task.finish(AsynchronousExecutor.java:188)
	at org.bukkit.craftbukkit.v1_7_R4.util.AsynchronousExecutor.finishActive(AsynchronousExecutor.java:347)
	at org.bukkit.craftbukkit.v1_7_R4.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:34)
	at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:607)
	at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:258)
	at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:558)
	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:469)
	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Linux (amd64) version 3.5.0-42-generic
	Java Version: 1.7.0_45, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 149994056 bytes (143 MB) / 545353728 bytes (520 MB) up to 1037959168 bytes (989 MB)
	JVM Flags: 24 total; -Xmx1024M -Xms256M -XX:MaxPermSize=128m -XX:PermSize=128m -XX:+DisableExplicitGC -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+UseNUMA -XX:+CMSParallelRemarkEnabled -XX:MaxGCPauseMillis=50 -XX:+UseAdaptiveGCBoundary -XX:-UseGCOverheadLimit -XX:+UseBiasedLocking -XX:SurvivorRatio=8 -XX:TargetSurvivorRatio=90 -XX:MaxTenuringThreshold=15 -XX:UseSSE=3 -XX:+UseLargePages -XX:+UseFastAccessorMethods -XX:+UseStringCache -XX:+UseCompressedStrings -XX:+UseCompressedOops -XX:+OptimizeStringConcat -XX:+AggressiveOpts
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	CraftBukkit Information: 
   Running: CraftBukkit version git-Bukkit-1.7.9-R0.2-16-g37c7969-b3105jnks (MC: 1.7.10) (Implementing API version 1.7.10-R0.1-SNAPSHOT) false
   Plugins: { NoCheatPlus v3.12.0-BETA2-sASO-b813 fr.neatmonster.nocheatplus.NoCheatPlus [NeatMonster, asofold, Evenprime], WorldEdit v6.0;3342-78f975b9 com.sk89q.worldedit.bukkit.WorldEditPlugin [], VoxelSniper v5.170.0-SNAPSHOT-jnks317-gitfcb8fe1 com.thevoxelbox.voxelsniper.VoxelSniper [przerwap, MikeMatrix, Gavjenks, giltwist, psanker, Deamon5550, DivineRage], MassiveCore v2.7.5 com.massivecraft.massivecore.MassiveCore [Cayorion], Vault v1.4.1-b436 net.milkbowl.vault.Vault [cereal, Sleaker, mung3r], PermissionsEx v1.22.8 ru.tehkode.permissions.bukkit.PermissionsEx [[t3hk0d3, zml]], Multiverse-Core v2.5-b691 com.onarandombox.MultiverseCore.MultiverseCore [Rigby, fernferret, lithium3141, main--], WorldGuard v5.9 com.sk89q.worldguard.bukkit.WorldGuardPlugin [], HeroicDeathPlus v2.5 org.mfles.plugin.heroicdeathtplus.HeroicDeath [SquallSeeD31, ElgarL, Slenky], MineResetLite v0.3.6 com.koletar.jj.mineresetlite.MineResetLite [jjkoletar], Bedwars v2.1.0 me.BukkitPVP.bedwars.Main [BukkitPVP], UHCRun v0.07 Beta com.galli24.uhcrun.UHCRun [], InfiniteDispensersAndDroppers v5.0.0 me.timpotim.idd.IDD [Timpotim], PerWorldPlugins v1.2.4 us.Myles.PWP.Plugin [_MylesC, Incomprehendable], CrackShot v0.98.1 com.shampaggon.crackshot.CSDirector [Shampaggon], EggWars v2.0 me.saphirant.eggWars.main.Main [saphirant], MyPet v1.2.1 de.Keyle.MyPet.MyPetPlugin [Keyle], HolographicDisplays v2.1.9 com.gmail.filoghost.holographicdisplays.HolographicDisplays [], HotPotato v1.2.1 me.avery246813579.hotpotato.HotPotato [], Essentials v2.13.1 com.earth2me.essentials.Essentials [Zenexer, ementalo, Aelux, Brettflan, KimKandor, snowleo, ceulemans, Xeology, KHobbits, md_5, Iaccidentally], ShowCaseStandalone v697 com.kellerkindt.scs.ShowCaseStandalone [kellerkindt, sorklin, bitfreeze, Ryzko, rtainc], EssentialsSpawn v2.13.1 com.earth2me.essentials.spawn.EssentialsSpawn [Zenexer, ementalo, Aelux, Brettflan, KimKandor, snowleo, ceulemans, Xeology, KHobbits], Multiverse-Inventories v2.5-b335 com.onarandombox.multiverseinventories.MultiverseInventories [dumptruckman], CreativeGates v2.7.5 com.massivecraft.creativegates.CreativeGates [Cayorion], AuthMe v3.5-SNAPSHOT fr.xephi.authme.AuthMe [Xephi59], EssentialsChat v2.13.1 com.earth2me.essentials.chat.EssentialsChat [Zenexer, ementalo, Aelux, Brettflan, KimKandor, snowleo, ceulemans, Xeology, KHobbits, md_5, Okamosy, Iaccidentally], Timeismoney v1.5 me.Phil.Timeismoney.Timeismoney [], WickedSkyWars v1.3.7-WordRedux1 com.mooglemods.wickedskywars.WickedSkyWars [HaxtorMoogle], Factions v2.7.5 com.massivecraft.factions.Factions [Cayorion, Brettflan],}
   Warnings: DEFAULT
   Threads: { WAITING Thread-5: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.park(LockSupport.java:186), java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2043), java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442), net.minecraft.util.com.mojang.util.QueueLogAppender.getNextLogEvent(QueueLogAppender.java:73), org.bukkit.craftbukkit.v1_7_R4.util.TerminalConsoleWriterThread.run(TerminalConsoleWriterThread.java:25), java.lang.Thread.run(Thread.java:744)], TIMED_WAITING MStore ExamineThread: [java.lang.Thread.sleep(Native Method), com.massivecraft.massivecore.store.ExamineThread.run(ExamineThread.java:55)], RUNNABLE Query Listener #1: [java.net.PlainDatagramSocketImpl.receive0(Native Method), java.net.AbstractPlainDatagramSocketImpl.receive(AbstractPlainDatagramSocketImpl.java:145), java.net.DatagramSocket.receive(DatagramSocket.java:786), net.minecraft.server.v1_7_R4.RemoteStatusListener.run(SourceFile:256), java.lang.Thread.run(Thread.java:744)], WAITING Reference Handler: [java.lang.Object.wait(Native Method), java.lang.Object.wait(Object.java:503), java.lang.ref.Reference$ReferenceHandler.run(Reference.java:133)], TIMED_WAITING Snooper Timer: [java.lang.Object.wait(Native Method), java.util.TimerThread.mainLoop(Timer.java:552), java.util.TimerThread.run(Timer.java:505)], RUNNABLE Server thread: [java.lang.Thread.dumpThreads(Native Method), java.lang.Thread.getAllStackTraces(Thread.java:1639), org.bukkit.craftbukkit.v1_7_R4.CraftCrashReport.call(CraftCrashReport.java:28), net.minecraft.server.v1_7_R4.CrashReportSystemDetails.a(SourceFile:74), net.minecraft.server.v1_7_R4.CrashReport.h(CrashReport.java:45), net.minecraft.server.v1_7_R4.CrashReport.<init>(CrashReport.java:33), net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:486), net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628)], WAITING Finalizer: [java.lang.Object.wait(Native Method), java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:135), java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:151), java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:189)], RUNNABLE DestroyJavaVM: [], RUNNABLE RCON Listener #2: [java.net.PlainSocketImpl.socketAccept(Native Method), java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:398), java.net.ServerSocket.implAccept(ServerSocket.java:530), java.net.ServerSocket.accept(ServerSocket.java:498), net.minecraft.server.v1_7_R4.RemoteControlListener.run(SourceFile:69), java.lang.Thread.run(Thread.java:744)], WAITING MV-Inv Profile Write Thread: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.park(LockSupport.java:186), java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2043), java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442), com.onarandombox.multiverseinventories.util.data.FlatFilePlayerData$FileWriteThread.run(FlatFilePlayerData.java:208)], RUNNABLE Netty IO #0: [sun.nio.ch.EPollArrayWrapper.epollWait(Native Method), sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269), sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:79), sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:87), sun.nio.ch.SelectorImpl.select(SelectorImpl.java:98), net.minecraft.util.io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:591), net.minecraft.util.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:301), net.minecraft.util.io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101), java.lang.Thread.run(Thread.java:744)], TIMED_WAITING Timer-0: [java.lang.Object.wait(Native Method), java.util.TimerThread.mainLoop(Timer.java:552), java.util.TimerThread.run(Timer.java:505)], RUNNABLE Signal Dispatcher: [], RUNNABLE Netty IO #2: [sun.nio.ch.EPollArrayWrapper.epollWait(Native Method), sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269), sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:79), sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:87), sun.nio.ch.SelectorImpl.select(SelectorImpl.java:98), net.minecraft.util.io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:591), net.minecraft.util.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:301), net.minecraft.util.io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101), java.lang.Thread.run(Thread.java:744)], WAITING Thread-15: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.park(LockSupport.java:186), java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2043), java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442), com.mooglemods.wickedskywars.storage.SQLStorage$SaveProcessor.run(SQLStorage.java:164), java.lang.Thread.run(Thread.java:744)], TIMED_WAITING File IO Thread: [java.lang.Thread.sleep(Native Method), net.minecraft.server.v1_7_R4.FileIOThread.b(SourceFile:44), net.minecraft.server.v1_7_R4.FileIOThread.run(SourceFile:23), java.lang.Thread.run(Thread.java:744)], WAITING Chunk I/O Executor Thread-1: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.park(LockSupport.java:186), java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2043), java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442), java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1068), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615), java.lang.Thread.run(Thread.java:744)], RUNNABLE Server console handler: [java.io.FileInputStream.readBytes(Native Method), java.io.FileInputStream.read(FileInputStream.java:272), java.io.BufferedInputStream.fill(BufferedInputStream.java:235), java.io.BufferedInputStream.read(BufferedInputStream.java:254), java.io.FilterInputStream.read(FilterInputStream.java:83), org.bukkit.craftbukkit.libs.jline.console.ConsoleReader$1.read(ConsoleReader.java:167), org.bukkit.craftbukkit.libs.jline.internal.InputStreamReader.read(InputStreamReader.java:267), org.bukkit.craftbukkit.libs.jline.internal.InputStreamReader.read(InputStreamReader.java:204), org.bukkit.craftbukkit.libs.jline.console.ConsoleReader.readCharacter(ConsoleReader.java:995), org.bukkit.craftbukkit.libs.jline.console.ConsoleReader.readLineSimple(ConsoleReader.java:1506), org.bukkit.craftbukkit.libs.jline.console.ConsoleReader.readLine(ConsoleReader.java:1153), org.bukkit.craftbukkit.libs.jline.console.ConsoleReader.readLine(ConsoleReader.java:1117), org.bukkit.craftbukkit.libs.jline.console.ConsoleReader.readLine(ConsoleReader.java:1105), net.minecraft.server.v1_7_R4.ThreadCommandReader.run(ThreadCommandReader.java:34)], WAITING pool-8-thread-1: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.park(LockSupport.java:186), java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2043), java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442), java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1068), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615), java.lang.Thread.run(Thread.java:744)], TIMED_WAITING pool-3-thread-18: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:226), java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:460), java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:359), java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:942), java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1068), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615), java.lang.Thread.run(Thread.java:744)], TIMED_WAITING Server Infinisleeper: [java.lang.Thread.sleep(Native Method), net.minecraft.server.v1_7_R4.ThreadSleepForever.run(SourceFile:63)], RUNNABLE Netty IO #1: [sun.nio.ch.EPollArrayWrapper.epollWait(Native Method), sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269), sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:79), sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:87), sun.nio.ch.SelectorImpl.select(SelectorImpl.java:98), net.minecraft.util.io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:591), net.minecraft.util.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:301), net.minecraft.util.io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101), java.lang.Thread.run(Thread.java:744)],}
   Recent tasks from 7499-7529{MassiveCore:com.massivecraft.massivecore.util.IdUtil@7229,}
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 100; [EntityPlayer['salem017'/781, l='world', x=17,44, y=148,22, z=14,49](salem017 at 17.44033712633458,148.21857049463281,14.493869888282049)]
	Is Modded: Definitely; Server brand changed to 'CraftBukkit'
	Type: Dedicated Server (map_server.txt)

LOG , the players are blocked in the same world , in the same place , can't leave to go play in a other minigames, anyfolder has created .
SI tu parles francais, les joueurs sont bloquée au meme endroit au meme moment meme s'ils sont dans un monde différent . Il ne peuvent pas quitter , je ne peux crée de monde et je ne peux pas aller loin aussi non le serveur crash .
