### ISSUE TITLE
UHC run 0.08

### ISSUE THREAD

**Issue by salem017** [Galli24/UHCRun#4]
J'espère que tu t'emmerdes :) . VOila le plugin me téléporte dans le ciel dans le monde world ( je ne peux pas changer le monde)  , il faudrait un fichier de config pour tp dans un lobby dans un monde différent , dire les choix d'équipes dans le serveur , et même peut etre de générer un monde juste pour ça . Franchement , ton plugin a beaucoup de potentiels , il faut juste regler ces pbs aprés c'est bon , j'essayerai de ne plus te faire chier :)

**Comment by Skylaa** [comment]
xD, enfaite c'est que certaine commande utilise le @a qui ne fonctionne pas en 1.7, de ce que j'ai vue sur la console

**Comment by Galli24** [comment]
T'as bien supprimé l'ancien monde avant de faire la nouvelle?? Parce que normalement y a un lobby, après niveau commandes je sais pas j'ai pas trop jouer en 1.7 donc bon :/

Après c'est sur que dans la 1.7 y a pas le mode spectateur, ce qui fait légèrement chier.

Pour le monde différent t'utilise un plugin de monde ainsi que définir ce plugin que dans ce monde ^^

Et tu fais pas chier, c'est bien que y a des gens comme toi qui me disent comment améliorer car je vois plus trop quoi ajouter^^

**Comment by salem017** [comment]
Bon galli24 , t'es pret pour une nuit blanche :) . Compatibilité et systemes de récompense vault  , création au démarage d'un fichier .yml ou on peut config le monde (regarde l'api du multiverse) , le lobby , et les préférences souhaitée ( langue française , les équipes ).

**Comment by Galli24** [comment]
Ouais, fin la semaine je suis pas dispo, puis j'ai mon bac de français donc bon xD

Vault viendra après la 1.0
La config aussi
Le lobby c'est déjà fait, alors je devrais tester^^
J'ai regardé la création d'un nouveau monde, je verrais bien si je pourrais bien l'intégrer^^

**Comment by salem017** [comment]
T'es en quel filiére ?

**Comment by Galli24** [comment]
En S ^^

**Comment by salem017** [comment]
et pour le fichier .yml qui se génére ?

**Comment by Galli24** [comment]
La config (le fichier yml) viendra sûrement dans la 1.0 ^^

**Comment by Skylaa** [comment]
Sinon pour le fichier de config j'ai quelques idées.

- Choisir le titre du scoreboard (useless mais toujours sympa)
- Choisir la langue par défaut au lancement du serveur.

Finallement, j'ai pas tant d'idée que ça xD

**Comment by salem017** [comment]
Bon tant qu'a faire je vais dire d'autre idée , une map générée aléatoirement +accée à un nether générée aléatoirement et collé sur la  carte + possiblité de faire une limite de map pour ce minijeu . Et bon bac de français galli :)

**Comment by Galli24** [comment]
Salem donne moi ton skype sinon xD
Je préfère le Nether pré fait comme c'est la
Limite de la map existe (1000x1000 en phase de préparation et 400x400 qui réduit a 10x10 en phase pvp)
Merci ;)

**Comment by salem017** [comment]
c'est salem017 ( je sais beaucoup d'imagination :) )

**Comment by salem017** [comment]
dis moi ton skype , je t'invite
